puts '** Insira abaixo o texto que deseja traduzir ** '
texto = gets.chomp
puts ''
puts 'Digite'
puts '## (0) Portugues     ->  Codigo Morse ##'
puts '## (1) Codigo Morse  ->     Portugues ##'
tradutor_arrow = gets.to_i
puts ''
print 'TRADUÇÃO'
puts ''

if tradutor_arrow == 0
    texto.each_char { |character|
        if character == 'a' or character == 'A'
            print '.-'
        elsif character == 'b' or character == 'B'
            print '-...'
        elsif character == 'c' or character == 'C'
            print '-.-.'
        elsif character == 'd' or character == 'D'
            print '-..'
        elsif character == 'e' or character == 'E'
            print '.'
        elsif character == 'f' or character == 'F'
            print '..-.'
        elsif character == 'g' or character == 'G'
            print '--.'
        elsif character == 'h' or character == 'H'
            print '....'
        elsif character == 'i' or character == 'I'
            print '..'
        elsif character == 'j' or character == 'J'
            print '.---'
        elsif character == 'k' or character == 'K'
            print '-.-'
        elsif character == 'l' or character == 'L'
            print '.-..'
        elsif character == 'm' or character == 'M'
            print '--'
        elsif character == 'n' or character == 'N'
            print '-.'
        elsif character == 'o' or character == 'O'
            print '---'
        elsif character == 'p' or character == 'P'
            print '.--.'
        elsif character == 'q' or character == 'Q'
            print '--.-'
        elsif character == 'r' or character == 'R'
            print '.-.'
        elsif character == 's' or character == 'S'
            print '...'
        elsif character == 't' or character == 'T'
            print '-'
        elsif character == 'u' or character == 'U'
            print '..-'
        elsif character == 'v' or character == 'V'
            print '...-'
        elsif character == 'w' or character == 'W'
            print '.--'
        elsif character == 'x' or character == 'X'
            print '-..-'
        elsif character == 'y' or character == 'Y'
            print '-.--'
        elsif character == 'z' or character == 'Z'
            print '--..'
        elsif character == ','
            print '--..--'
        elsif character == '.'
            print '.-.-.-'
        elsif character == '?'
            print '..--..'
        elsif character == '!'
            print '-·-·--'
        elsif character == ':'
            print '---···'
        elsif character == ';'
            print '-·-·-·'
        elsif character == ' '
            print '/'
        elsif character == '$'
            print '···-··-'
        elsif character == '('
            print '-·--·'
        elsif character == ')'
            print '-·--·-'
        else
            puts ''
            puts 'Erro! Esse caracter nao existe no banco de dados.'
            break
        end
        print ' '
    }
    puts ''
elsif tradutor_arrow == 1
    loop do
        character = ''
        texto.each_char { |i|
            if i == ' '
                texto.slice!(0)
                break
            elsif texto == ''
                break
                # se o texto estiver vazio o programa realiza a ultima traduçao
            end
            character.concat(i)
            texto.slice!(0)
        }
        if character == '.-'
            print 'a'
        elsif character == '-...'
            print 'b'
        elsif character == '-.-.'
            print 'c'
        elsif character == '-..'
            print 'd'
        elsif character == '.'
            print 'e'
        elsif character == '..-.'
            print 'f'
        elsif character == '--.'
            print 'g'
        elsif character == '....'
            print 'h'
        elsif character == '..'
            print 'i'
        elsif character == '.---'
            print 'j'
        elsif character == '-.-'
            print 'k'
        elsif character == '.-..'
            print 'l'
        elsif character == '--'
            print 'm'
        elsif character == '-.'
            print 'n'
        elsif character == '---'
            print 'o'
        elsif character == '.--.'
            print 'p'
        elsif character == '--.-'
            print 'q'
        elsif character == '.-.'
            print 'r'
        elsif character == '...'
            print 's'
        elsif character == '-'
            print 't'
        elsif character == '..-'
            print 'u'
        elsif character == '...-'
            print 'v'
        elsif character == '.--'
            print 'w'
        elsif character == '-..-'
            print 'x'
        elsif character == '-.--'
            print 'y'
        elsif character == '--..'
            print 'z'
        elsif character == '--..--'
            print ','
        elsif character == '.-.-.-'
            print '.'
        elsif character == '..--..'
            print '?'
        elsif character == '-·-·--'
            print '!'
        elsif character == '---···'
            print ':'
        elsif character == '-·-·-·'
            print ';'
        elsif character == ' '
            print ''
        elsif character == '/'
            print ' '
        elsif character == '···-··-'
            print '$'
                elsif character == '-·--·'
            print '('
        elsif character == '-·--·-'
            print ')'
        else
            puts ''
            puts 'Erro! Esse caracter nao existe no banco de dados.'
            break
        end
    if texto == ''
        break
        # se o texto estiver vazio, o programa sai do loop..do
    end
    end
else
    print 'Erro, nenhuma alternativa selecionada!'
end
